logging:
    level:
      org.jsahad: INFO

data:
  static:
    jsonFile: src/main/resources/source-data.json


management:
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: prometheus, info, health, metrics
